dist: focal

env:
  global:
    - CC_TEST_REPORTER_ID=5cfed40102c670b5c9e509730782b751939ddbe53fc57c317b718f635bab1ce8
  jobs:
    - PUPPETEER_VERSION=1.20.0
    - PUPPETEER_VERSION=2.1.1
    - PUPPETEER_VERSION=3.3.0
    - PUPPETEER_VERSION=4.0.1
    - PUPPETEER_VERSION=5.5.0
    - PUPPETEER_VERSION=6.0.0
    - PUPPETEER_VERSION=7.1.0
    - PUPPETEER_VERSION=8.0.0
    - PUPPETEER_VERSION=9.1.1
    - PUPPETEER_VERSION=10.4.0
    - PUPPETEER_VERSION=11.0.0
    - PUPPETEER_VERSION=12.0.1

rvm: 3.0

jobs:
  include:
    - rvm: 2.6
      env: PUPPETEER_VERSION=12.0.1
    - rvm: 2.7
      env: PUPPETEER_VERSION=12.0.1
    - rvm: ruby-head
      env: PUPPETEER_VERSION=12.0.1

language: ruby

before_install:
  - nvm install 10
  - gem update bundler

install:
  - bundle install --jobs=3 --retry=3
  - gem install rubocop
  - npm install puppeteer@$PUPPETEER_VERSION

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rubocop
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
